### ISSUE TITLE
An exception is thrown immediately after selecting HTML graphics

### ISSUE THREAD

**Issue by duskalbatross** [gapitio/gapit-htmlgraphics-panel#78]
**What happened**:
After installing the plugin and selecting the HTML graphics, an exception is thrown immediately: 

An unexpected error happened
Detail: 
Error: Illegal value for token color: #fff

    at me (http://localhost:3000/public/build/react-monaco-editor.fb13e4673cc0c41043f4.js:1:15930)
    at Ps (http://localhost:3000/public/build/467.fb13e4673cc0c41043f4.js:2162:3757)
    at div
    at Ls (http://localhost:3000/public/build/467.fb13e4673cc0c41043f4.js:2162:5745)
    at WithTheme(undefined)
    at div
    at w (http://localhost:3000/public/plugins/gapit-htmlgraphics-panel/module.js:1:16459)
    at _ (http://localhost:3000/public/plugins/gapit-htmlgraphics-panel/module.js:1:19510)
    at div
    at div
    at p (http://localhost:3000/public/build/467.fb13e4673cc0c41043f4.js:422:27)
    at div
    at div
    at http://localhost:3000/public/build/DashboardPage.fb13e4673cc0c41043f4.js:199:2304
    at div
    at div
    at div
    at t (http://localhost:3000/public/build/2256.fb13e4673cc0c41043f4.js:2:775078)
    at u (http://localhost:3000/public/build/467.fb13e4673cc0c41043f4.js:290:968)
    at div
    at div
    at zn (http://localhost:3000/public/build/DashboardPage.fb13e4673cc0c41043f4.js:275:590)
    at div
    at div
    at tr (http://localhost:3000/public/build/DashboardPage.fb13e4673cc0c41043f4.js:393:507)
    at div
    at t (http://localhost:3000/public/build/DashboardPage.fb13e4673cc0c41043f4.js:426:3209)
    at div
    at t (http://localhost:3000/public/build/DashboardPage.fb13e4673cc0c41043f4.js:426:5160)
    at _r (http://localhost:3000/public/build/DashboardPage.fb13e4673cc0c41043f4.js:426:10770)
    at div
    at div
    at ia (http://localhost:3000/public/build/DashboardPage.fb13e4673cc0c41043f4.js:486:6031)
    at g (http://localhost:3000/public/build/2256.fb13e4673cc0c41043f4.js:2:1083974)
    at div
    at Mi (http://localhost:3000/public/build/DashboardPage.fb13e4673cc0c41043f4.js:574:3583)
    at DashboardPage
    at g (http://localhost:3000/public/build/2256.fb13e4673cc0c41043f4.js:2:1083974)
    at n (http://localhost:3000/public/build/2256.fb13e4673cc0c41043f4.js:2:1053444)
    at so (http://localhost:3000/public/build/467.fb13e4673cc0c41043f4.js:6608:181)
    at t (http://localhost:3000/public/build/2256.fb13e4673cc0c41043f4.js:2:1101712)
    at t (http://localhost:3000/public/build/2256.fb13e4673cc0c41043f4.js:2:1103733)
    at main
    at t (http://localhost:3000/public/build/2256.fb13e4673cc0c41043f4.js:2:1098330)
    at div
    at Qs (http://localhost:3000/public/build/467.fb13e4673cc0c41043f4.js:2171:1055)
    at d (http://localhost:3000/public/build/467.fb13e4673cc0c41043f4.js:4495:26220)
    at _l (http://localhost:3000/public/build/467.fb13e4673cc0c41043f4.js:2883:467)
    at Nl (http://localhost:3000/public/build/467.fb13e4673cc0c41043f4.js:2883:1023)
    at l (http://localhost:3000/public/build/2256.fb13e4673cc0c41043f4.js:2:1081540)
    at Ho (http://localhost:3000/public/build/467.fb13e4673cc0c41043f4.js:6688:384)

**What you expected to happen**:
Show the panel edit page.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install the plugin using command line: 
`grafana-cli --pluginsDir "/Users/lyh/dev/src/grafana/plugins" plugins install gapit-htmlgraphics-panel`
2. Create a panel.
3. Select HTML graphics in the dropdown list.

**Anything else we need to know?**:

**Environment**:

- Grafana version: 8.3.3
- Plugin (gapit-htmlgraphics-panel) version: 2.0.1
- Data source type & version: build in datasource --Grafana--
- OS Grafana is installed on: macOS Monterey 12.1
- User OS & Browser: 97.0.4692.71 arm64
- Grafana plugins: 
- Others:

**Comment by duskalbatross** [comment]
After I upgrade my grafana to 8.3.4, an error  is shown instead.
![image](https://user-images.githubusercontent.com/12107982/150047108-3c6a9627-ca5b-4a7c-9267-1deb20b5d1aa.png)

**Comment by duskalbatross** [comment]
> After I upgrade my grafana to 8.3.4, an error is shown instead. ![image](https://user-images.githubusercontent.com/12107982/150047108-3c6a9627-ca5b-4a7c-9267-1deb20b5d1aa.png)

And the console's message:
![image](https://user-images.githubusercontent.com/12107982/150048025-d7720a49-ece2-40a6-acd6-7e65d4c5cc4a.png)

**Comment by neshorg** [comment]
I just wanted to add that I got the same error when testing Grafana version  8.3.4. So I rolled back to 8.3.3 for now which still works on my end.

**Comment by KunjanThadani** [comment]
Got the same problem in Grafana version 8.3.4 for Plugin (gapit-htmlgraphics-panel) version: 2.0.1
Works fine with Plugin (gapit-htmlgraphics-panel) version: 2.0.0

**Comment by ZuperZee** [comment]
Just to follow up. The reason for this is because Grafana removed tslib from the toolkit from [Grafana v8.3.4](https://github.com/grafana/grafana/releases/tag/v8.3.4). [PR #43556](https://github.com/grafana/grafana/pull/43556).
